// Archivo de traducciones - Simplificado y completado
const TRADUCCIONES = {
    es: {
        // ===== APP =====
        app: {
            titulo: 'Dashboard Económico'
        },

        // ===== TEMAS =====
        temas: {
            azul: 'Azul Profesional',
            verde: 'Verde Moderno',
            naranja: 'Naranja Energético',
            turquesa: 'Turquesa Fresco',
            purpura: 'Púrpura Moderno',
            rojo: 'Rojo Elegante',
            indigo: 'Índigo Suave',
            teal: 'Teal Profesional',
            gris: 'Gris Corporativo',
            rosado: 'Rosado Moderno',
            cian: 'Cian Vibrante',
            lima: 'Lima Fresco',
            esmeralda: 'Esmeralda Premium',
            ambar: 'Ámbar Dorado',
            violeta: 'Violeta Místico',
            fresa: 'Fresa Rosa',
            oceano: 'Océano Profundo',
            bosque: 'Bosque Verde',
            atardecer: 'Atardecer',
            medianoche: 'Medianoche Oscuro',
            neon: 'Neón Ciberpunk',
            mint: 'Mint Suave',
            coral: 'Coral Tropical',
            lavanda: 'Lavanda Elegante',
            grisminimal: 'Gris Minimalista',
            bronce: 'Bronce Vintage',
            cielo: 'Cielo Claro'
        },

        // ===== PERÍODOS =====
        periodos: {
            un_mes: '1 Mes',
            tres_meses: '3 Meses',
            seis_meses: '6 Meses',
            un_anio: '1 Año',
            cinco_anios: '5 Años',
            diez_anios: '10 Años'
        },

        // ===== RESUMEN =====
        resumen: {
            totalIngresos: 'Total Ingresos',
            totalGastos: 'Total Gastos',
            saldo: 'Saldo',
            totalImpuestos: 'Total Impuestos',
            impuestosPre: 'Pre',
            impuestosPost: 'Post',
            totalHucha: 'Total Hucha',
            portfolioRendimiento: 'Rendimiento Portfolio'
        },

        // ===== TEMA =====
        tema: {
            cambiarTema: '🎨 Tema:',
            seleccionar: 'Seleccionar tema',
            claro: 'Claro',
            oscuro: 'Oscuro',
            automático: 'Automático'
        },

        // ===== IDIOMA =====
        idioma: {
            seleccionar: '🌐 Idioma:',
            espanol: 'Español',
            ingles: 'English',
            portugues: 'Português',
            frances: 'Français',
            euskera: 'Euskara'
        },
        hucha: {
            concepto: 'Concepto',
            cantidad: 'Cantidad'
        },

        // ===== NAVEGACIÓN =====
        nav: {
            categorias: 'Categorías',
            gastos: 'Gastos',
            ingresos: 'Ingresos',
            impuestos: 'Impuestos',
            dashboard: 'Dashboard',
            hucha: 'Hucha Real'
        },

        // ===== DASHBOARD =====
        dashboard: {
            titulo: 'Resumen Financiero',
            periodoRapido: 'Período Rápido',
            desde: 'Desde',
            hasta: 'Hasta',
            desdeDate: 'Selecciona fecha de inicio',
            hastaDate: 'Selecciona fecha de fin',
            actualizar: 'Actualizar',
            totalPeriodo: 'Totales Período',
            gastosPorMes: 'Gastos por Mes',
            todasCategorias: 'Todas las categorías',
            ingresos: 'Ingresos',
            gastos: 'Gastos',
            ahorros: 'Ahorros',
            ingresosPorCategoria: 'Ingresos por Categoría',
            gastosPorCategoria: 'Gastos por Categoría',
            media: 'Media',
            varianza: 'Varianza',
            desviacion: 'Desviación',
            mediaMensualTotal: 'Media mensual total',
            impuestosCategoria: 'Impuestos',
            errorHastaMenorDesde: 'La fecha "hasta" no puede ser menor que "desde"',
            seleccionaRango: 'Por favor selecciona un rango de fechas'
        },

        // ===== CATEGORÍAS =====
        categorias: {
            titulo: 'Administrar Categorías',
            gastos: 'Gastos',
            ingresos: 'Ingresos',
            categoriasGasto: 'Categorías de Gasto',
            categoriasIngreso: 'Categorías de Ingreso',
            nuevaCategoria: 'Nueva categoría...',
            noHayCategoriasGasto: 'No hay categorías de gasto',
            noHayCategoriasIngreso: 'No hay categorías de ingreso',
            categoriaAgregada: 'Categoría agregada correctamente',
            categoriaEliminada: 'Categoría eliminada correctamente',
            categoriaActualizada: 'Categoría actualizada correctamente'
        },

        // ===== GASTOS =====
        gastos: {
            titulo: 'Administrar Gastos',
            puntuales: 'Gastos Puntuales',
            mensuales: 'Gastos Mensuales',
            descripcion: 'Descripción...',
            desde: 'Desde',
            hasta: 'Hasta',
            monto: 'Monto',
            mostrarAntiguos: 'Mostrar antiguos',
            ocultarAntiguos: 'Ocultar antiguos',
            fraccionar: 'Fraccionar',
            noHayGastos: 'No hay gastos registrados',
            gastoAgregado: 'Gasto agregado correctamente',
            gastoEliminado: 'Gasto eliminado correctamente',
            gastoActualizado: 'Gasto actualizado correctamente',
            validarFecha: 'Por favor selecciona una fecha válida',
            validarMonto: 'Por favor ingresa un monto válido',
            validarCategoria: 'Por favor selecciona una categoría'
        },

        // ===== INGRESOS =====
        ingresos: {
            titulo: 'Administrar Ingresos',
            puntuales: 'Ingresos Puntuales',
            mensuales: 'Ingresos Mensuales',
            cuenta_remunerada: 'Cuenta Remunerada',
            descripcion: 'Descripción...',
            desde: 'Desde',
            hasta: 'Hasta',
            bruto: 'Bruto',
            aportacionInicial: 'Aportación Inicial',
            aportacionMensual: 'Aportación Mensual',
            interes: 'Interés (%)',
            interesGenerado: 'Interés Generado',
            mostrarAntiguos: 'Mostrar antiguos',
            ocultarAntiguos: 'Ocultar antiguos',
            noHayIngresos: 'No hay ingresos registrados',
            ingresoAgregado: 'Ingreso agregado correctamente',
            ingresoEliminado: 'Ingreso eliminado correctamente',
            ingresoActualizado: 'Ingreso actualizado correctamente',
            validarFecha: 'Por favor selecciona una fecha válida',
            validarMonto: 'Por favor ingresa un monto válido',
            validarCategoria: 'Por favor selecciona una categoría',
            assets: 'Assets',
            noHayCambios: 'No hay cambios',
            descripcionRequerida: 'Descripción requerida',
            categoriaRequerida: 'Categoría requerida',
            montoInvalido: 'Monto inválido',
            fechaRequerida: 'Fecha requerida',
            formatoDesde: "El campo 'Desde' debe tener formato YYYY-MM",
            formatoHasta: "El campo 'Hasta' debe tener formato YYYY-MM",
            aportacionInvalida: 'Aportación mensual inválida',
            interesInvalido: 'Interés inválido',
            seleccionaFecha: 'Selecciona una fecha',
            ingresaDescripcion: 'Ingresa una descripción',
            seleccionaCategoria: 'Selecciona una categoría',
            ingresaDesde: "Ingresa el mes 'desde' en formato YYYY-MM",
            ingresaHasta: "Ingresa el mes 'hasta' en formato YYYY-MM",
            montoInicialInvalido: 'Monto inicial inválido',
            desdeNoMayorHasta: "El mes 'desde' no puede ser mayor que 'hasta'",
            ingresaNombreCompania: 'Ingresa el nombre de la compañía',
            ingresaTicker: 'Ingresa el ticker',
            accionesInvalidas: 'Número de acciones inválido',
            precioCompraInvalido: 'Precio de compra inválido',
            precioVentaInvalido: 'Por favor ingresa un precio de venta válido',
            confirmarVenta: '¿Confirmar venta de {shares} acciones de {company} a {price} por acción?',
            ventaExitosa: 'Venta exitosa. Ganancia registrada: {profit}',
            errorVenta: 'Error: {error}',
            errorProcesarVenta: 'Error al procesar la venta',
            eliminarAsset: '¿Eliminar este asset?',
            company: 'Compañía',
            ticker: 'Ticker',
            shares: 'Acciones',
            purchasePrice: 'Precio Compra',
            totalInvestment: 'Total Invertido',
            currentPrice: 'Precio Actual',
            currentValue: 'Valor Actual',
            diffPercent: 'Dif. %',
            diffAmount: 'Dif. €',
            sellAsset: 'Vender Asset',
            salePrice: 'Precio de Venta',
            saleValue: 'Valor Venta',
            profit: 'Ganancia/Pérdida',
            confirmSale: 'Confirmar Venta',
            placeholderDescripcion: 'Descripción...',
            placeholderMonto: '0.00',
            placeholderYYYYMM: 'YYYY-MM',
            placeholderCompany: 'Apple Inc.',
            placeholderTicker: 'AAPL',
            placeholderShares: '10',
            placeholderPrice: '150.00'
        },

        // ===== IMPUESTOS =====
        taxes: {
            agregarPuntual: 'Agregar Impuesto Puntual',
            agregarMensual: 'Agregar Impuesto Mensual',
            impuestoAgregado: 'Impuesto agregado correctamente',
            impuestoEliminado: 'Impuesto eliminado correctamente',
            impuestoActualizado: 'Impuesto actualizado correctamente',
            desde: 'Desde',
            hasta: 'Hasta'
        },

        // ===== FORMULARIOS =====
        formularios: {
            guardar: 'Guardar',
            cancelar: 'Cancelar',
            editar: 'Editar',
            eliminar: 'Eliminar',
            agregar: 'Agregar',
            buscar: 'Buscar',
            nombre: 'Nombre',
            descripcion: 'Descripción',
            cantidad: 'Cantidad',
            monto: 'Monto',
            categoria: 'Categoría',
            fecha: 'Fecha',
            desde: 'Desde',
            hasta: 'Hasta',
            bruto: 'Bruto',
            interes: 'Interés',
            accion: 'Acción',
            acciones: 'Acciones',
            obligatorio: 'Campo obligatorio',
            confirmarEliminar: '¿Estás seguro de que deseas eliminar esto?',
            si: 'Sí',
            no: 'No',
            cerrar: 'Cerrar',
            aceptar: 'Aceptar',
            rechazar: 'Rechazar'
        },

        // ===== BOTONES =====
        botones: {
            agregar: 'Agregar',
            actualizar: 'Actualizar',
            editar: 'Editar',
            eliminar: 'Eliminar',
            guardar: 'Guardar',
            cancelar: 'Cancelar'
        },

        // ===== TABS =====
        tabs: {
            puntuales: 'Puntuales',
            mensuales: 'Mensuales'
        },

        // ===== MENSAJES =====
        mensajes: {
            exito: 'Operación completada exitosamente',
            error: 'Ocurrió un error',
            cargando: 'Cargando...',
            noHayDatos: 'No hay datos disponibles',
            seleccionaRango: 'Selecciona un rango de fechas',
            categoriasCargadas: 'Categorías cargadas',
            dashboardActualizado: 'Dashboard actualizado',
            errorCargando: 'Error cargando datos',
            errorGuardando: 'Error guardando datos',
            errorEliminando: 'Error eliminando datos',
            validacionError: 'Por favor rellena todos los campos obligatorios',
            confirmacion: 'Confirmación requerida'
        },

        // ===== TABLAS =====
        tablas: {
            sinResultados: 'Sin resultados',
            fecha: 'Fecha',
            descripcion: 'Descripción',
            monto: 'Monto',
            categoria: 'Categoría',
            acciones: 'Acciones',
            cargando: 'Cargando...',
            mostrandoRegistros: 'Mostrando {0} de {1} registros',
            siguiente: 'Siguiente',
            anterior: 'Anterior',
            primera: 'Primera',
            ultima: 'Última',
            porPagina: 'Registros por página'
        },

        // ===== ERRORES =====
        errores: {
            campoObligatorio: 'Este campo es obligatorio',
            formatoInvalido: 'Formato inválido',
            montoNegativo: 'El monto no puede ser negativo',
            fechaInvalida: 'Fecha inválida',
            seleccionaCategoria: 'Debes seleccionar una categoría',
            seleccionaFecha: 'Debes seleccionar una fecha',
            sinConexion: 'Error de conexión',
            tiempoAgotado: 'Tiempo de conexión agotado'
        },

        // ===== CONFIRMACIONES =====
        confirmaciones: {
            guardar: '¿Deseas guardar los cambios?',
            eliminar: '¿Estás seguro de que deseas eliminar este elemento?',
            cancelar: '¿Deseas cancelar esta operación?',
            salirSinGuardar: '¿Deseas salir sin guardar los cambios?'
        }
    },

    eu: {
        app: {
            titulo: 'Finantza Arbel'
        },
        temas: {
            azul: 'Urdin Profesionala',
            verde: 'Berde Modernoa',
            naranja: 'Laranja Energetikoa',
            turquesa: 'Turkesa Freskoa',
            purpura: 'More Modernoa',
            rojo: 'Gorri Dotorea',
            indigo: 'Indigo Leuna',
            teal: 'Teal Profesionala',
            gris: 'Gris Korporatiboa',
            rosado: 'Arrosa Modernoa',
            cian: 'Cian Bizia',
            lima: 'Lima Freskoa',
            esmeralda: 'Esmeralda Premium',
            ambar: 'Amber Urre',
            violeta: 'Bioleta Mistikua',
            fresa: 'Marrubi Arrosa',
            oceano: 'Ozeano Sakona',
            bosque: 'Basoa Berdea',
            atardecer: 'Ilunabarra',
            medianoche: 'Gauerdiko Iluna',
            neon: 'Neon Ziberpunk',
            mint: 'Menda Leuna',
            coral: 'Koralezko Tropikala',
            lavanda: 'Laranja Dotorea',
            grisminimal: 'Gris Minimalista',
            bronce: 'Brontze Vintage',
            cielo: 'Zeru Garbia'
        },
        periodos: {
            un_mes: '1 Hilabete',
            tres_meses: '3 Hilabete',
            seis_meses: '6 Hilabete',
            un_anio: '1 Urte',
            cinco_anios: '5 Urte',
            diez_anios: '10 Urte'
        },
        resumen: {
            totalIngresos: 'Sarrera Guztira',
            totalGastos: 'Gastu Guztira',
            saldo: 'Saldoa',
            totalImpuestos: 'Zergen Guztira',
            impuestosPre: 'Aurre',
            impuestosPost: 'Ondoren',
            totalHucha: 'Kutxa Guztira'
        },
        tema: {
            cambiarTema: '🎨 Gaia:',
            seleccionar: 'Gaia aukeratu',
            claro: 'Argia',
            oscuro: 'Iluna',
            automático: 'Automatikoa'
        },
        idioma: {
            seleccionar: '🌐 Hizkuntza:',
            espanol: 'Espainiera',
            ingles: 'Ingelesa',
            portugues: 'Portugesa',
            frances: 'Frantsesa',
            euskera: 'Euskara'
        },
        hucha: {
            concepto: 'Kontzeptua',
            cantidad: 'Kopurua'
        },
        nav: {
            categorias: 'Kategoriak',
            gastos: 'Gastua',
            ingresos: 'Sarrerak',
            impuestos: 'Zergak',
            dashboard: 'Arbela',
            hucha: 'Kutxa'
        },
        dashboard: {
            titulo: 'Laburpen Finantzarioa',
            periodoRapido: 'Epe Azkarra',
            desde: 'Noiztik',
            hasta: 'Noiz arte',
            desdeDate: 'Hasiera data aukeratu',
            hastaDate: 'Amaiera data aukeratu',
            actualizar: 'Eguneratu',
            totalPeriodo: 'Epearen Guztira',
            gastosPorMes: 'Hilabeteko Gastuak',
            todasCategorias: 'Kategoria guztiak',
            ingresos: 'Sarrerak',
            gastos: 'Gastua',
            ahorros: 'Aurreztuak',
            ingresosPorCategoria: 'Kategoriaren araberako sarrerak',
            gastosPorCategoria: 'Kategoriaren araberako gastuak',
            media: 'Batazbestekoa',
            varianza: 'Bariazioa',
            desviacion: 'Desbiderapena',
            mediaMensualTotal: 'Hilabeteko batazbesteko guztira',
            impuestosCategoria: 'Zergak',
            errorHastaMenorDesde: 'Amaiera data ezin da hasiera data baino lehenago izan',
            seleccionaRango: 'Aukeratu data tarte bat'
        },
        categorias: {
            titulo: 'Kategoriak Kudeatu',
            gastos: 'Gastua',
            ingresos: 'Sarrerak',
            categoriasGasto: 'Gastu Kategoriak',
            categoriasIngreso: 'Sarrera Kategoriak',
            nuevaCategoria: 'Kategoria berria...',
            noHayCategoriasGasto: 'Ez dago gastu kategoriarik',
            noHayCategoriasIngreso: 'Ez dago sarrera kategoriarik',
            categoriaAgregada: 'Kategoria ondo gehitu da',
            categoriaEliminada: 'Kategoria ondo ezabatu da',
            categoriaActualizada: 'Kategoria ondo eguneratu da'
        },
        gastos: {
            titulo: 'Gastua Kudeatu',
            puntuales: 'Behin-behineko Gastuak',
            mensuales: 'Hileko Gastuak',
            descripcion: 'Deskribapena...',
            desde: 'Noiztik',
            hasta: 'Noiz arte',
            monto: 'Zenbatekoa',
            mostrarAntiguos: 'Zaharrak erakutsi',
            ocultarAntiguos: 'Zaharrak ezkutatu',
            fraccionar: 'Zatitu',
            noHayGastos: 'Ez dago gasturik',
            gastoAgregado: 'Gastu ondo gehitu da',
            gastoEliminado: 'Gastu ondo ezabatu da',
            gastoActualizado: 'Gastu ondo eguneratu da',
            validarFecha: 'Mesedez, hautatu data egoki bat',
            validarMonto: 'Mesedez, sartu zenbateko egoki bat',
            validarCategoria: 'Mesedez, hautatu kategoria bat'
        },
        ingresos: {
            titulo: 'Sarrerak Kudeatu',
            puntuales: 'Behin-behineko Sarrerak',
            mensuales: 'Hileko Sarrerak',
            cuenta_remunerada: 'Errentadun Kontua',
            descripcion: 'Deskribapena...',
            desde: 'Noiztik',
            hasta: 'Noiz arte',
            bruto: 'Gordina',
            aportacionInicial: 'Hasierako Ekarpena',
            aportacionMensual: 'Hileko Ekarpena',
            interes: 'Interesa (%)',
            interesGenerado: 'Sortutako Interesa',
            mostrarAntiguos: 'Zaharrak erakutsi',
            ocultarAntiguos: 'Zaharrak ezkutatu',
            noHayIngresos: 'Ez dago sarrerarik',
            ingresoAgregado: 'Sarrera ondo gehitu da',
            ingresoEliminado: 'Sarrera ondo ezabatu da',
            ingresoActualizado: 'Sarrera ondo eguneratu da',
            validarFecha: 'Mesedez, hautatu data egoki bat',
            validarMonto: 'Mesedez, sartu zenbateko egoki bat',
            validarCategoria: 'Mesedez, hautatu kategoria bat',
            assets: 'Aktiboak',
            noHayCambios: 'Ez dago aldaketarik',
            descripcionRequerida: 'Deskribapena beharrezkoa da',
            categoriaRequerida: 'Kategoria beharrezkoa da',
            montoInvalido: 'Zenbateko baliogabea',
            fechaRequerida: 'Data beharrezkoa da',
            formatoDesde: "'Noiztik' eremuak UUUU-HH formatua izan behar du",
            formatoHasta: "'Noiz arte' eremuak UUUU-HH formatua izan behar du",
            aportacionInvalida: 'Hileko ekarpen baliogabea',
            interesInvalido: 'Interes baliogabea',
            seleccionaFecha: 'Hautatu data bat',
            ingresaDescripcion: 'Sartu deskribapen bat',
            seleccionaCategoria: 'Hautatu kategoria bat',
            ingresaDesde: "Sartu 'noiztik' hilabetea UUUU-HH formatuan",
            ingresaHasta: "Sartu 'noiz arte' hilabetea UUUU-HH formatuan",
            montoInicialInvalido: 'Hasierako zenbateko baliogabea',
            desdeNoMayorHasta: "'Noiztik' hilabetea ezin da handiagoa izan 'noiz arte' baino",
            ingresaNombreCompania: 'Sartu enpresaren izena',
            ingresaTicker: 'Sartu ticker-a',
            accionesInvalidas: 'Akzio kopuru baliogabea',
            precioCompraInvalido: 'Erosketa prezio baliogabea',
            precioVentaInvalido: 'Mesedez, sartu salmenta prezio egoki bat',
            confirmarVenta: 'Berretsi {company} enpresako {shares} akzio {price}-an akzioko salmenta?',
            ventaExitosa: 'Salmenta arrakastatsua. Erregistratutako irabazia: {profit}',
            errorVenta: 'Errorea: {error}',
            errorProcesarVenta: 'Errorea salmenta prozesatzean',
            eliminarAsset: 'Aktibo hau ezabatu?',
            company: 'Enpresa',
            ticker: 'Ticker',
            shares: 'Akzioak',
            purchasePrice: 'Erosketa Prezioa',
            totalInvestment: 'Guztira Inbertituta',
            currentPrice: 'Uneko Prezioa',
            currentValue: 'Uneko Balioa',
            diffPercent: 'Dif. %',
            diffAmount: 'Dif. €',
            sellAsset: 'Aktibo Saldu',
            salePrice: 'Salmenta Prezioa',
            saleValue: 'Salmenta Balioa',
            profit: 'Irabazia/Galera',
            confirmSale: 'Salmenta Berretsi',
            placeholderDescripcion: 'Deskribapena...',
            placeholderMonto: '0.00',
            placeholderYYYYMM: 'UUUU-HH',
            placeholderCompany: 'Apple Inc.',
            placeholderTicker: 'AAPL',
            placeholderShares: '10',
            placeholderPrice: '150.00'
        },
        taxes: {
            agregarPuntual: 'Behin-behineko Zerga Gehitu',
            agregarMensual: 'Hileko Zerga Gehitu',
            impuestoAgregado: 'Zerga ondo gehitu da',
            impuestoEliminado: 'Zerga ondo ezabatu da',
            impuestoActualizado: 'Zerga ondo eguneratu da',
            desde: 'Noiztik',
            hasta: 'Noiz arte'
        },
        formularios: {
            guardar: 'Gorde',
            cancelar: 'Utzi',
            editar: 'Editatu',
            eliminar: 'Ezabatu',
            agregar: 'Gehitu',
            buscar: 'Bilatu',
            nombre: 'Izena',
            descripcion: 'Deskribapena',
            cantidad: 'Kopurua',
            monto: 'Zenbatekoa',
            categoria: 'Kategoria',
            fecha: 'Data',
            desde: 'Noiztik',
            hasta: 'Noiz arte',
            bruto: 'Gordina',
            interes: 'Interesa',
            accion: 'Ekintza',
            acciones: 'Ekintzak',
            obligatorio: 'Derrigorrezko eremua',
            confirmarEliminar: 'Ziur zaude hau ezabatu nahi duzula?',
            si: 'Bai',
            no: 'Ez',
            cerrar: 'Itxi',
            aceptar: 'Onartu',
            rechazar: 'Baztertu'
        },
        botones: {
            agregar: 'Gehitu',
            actualizar: 'Eguneratu',
            editar: 'Editatu',
            eliminar: 'Ezabatu',
            guardar: 'Gorde',
            cancelar: 'Utzi'
        },
        tabs: {
            puntuales: 'Behin-behinekoak',
            mensuales: 'Hilekoak'
        },
        mensajes: {
            exito: 'Eragiketa ondo burutu da',
            error: 'Errore bat gertatu da',
            cargando: 'Kargatzen...',
            noHayDatos: 'Ez dago daturik',
            seleccionaRango: 'Aukeratu data tarte bat',
            categoriasCargadas: 'Kategoriak kargatuta',
            dashboardActualizado: 'Arbela eguneratuta',
            errorCargando: 'Errorea datuak kargatzean',
            errorGuardando: 'Errorea datuak gordetzean',
            errorEliminando: 'Errorea datuak ezabatzean',
            validacionError: 'Mesedez, bete derrigorrezko eremu guztiak',
            confirmacion: 'Berrespena beharrezkoa'
        },
        tablas: {
            sinResultados: 'Emaitzarik ez',
            fecha: 'Data',
            descripcion: 'Deskribapena',
            monto: 'Zenbatekoa',
            categoria: 'Kategoria',
            acciones: 'Ekintzak',
            cargando: 'Kargatzen...',
            mostrandoRegistros: '{0} / {1} erregistro erakusten',
            siguiente: 'Hurrengoa',
            anterior: 'Aurrekoa',
            primera: 'Lehena',
            ultima: 'Azkena',
            porPagina: 'Erregistroak orrialdeko'
        },
        errores: {
            campoObligatorio: 'Eremu hau derrigorrezkoa da',
            formatoInvalido: 'Formatu baliogabea',
            montoNegativo: 'Zenbatekoa ezin da negatiboa izan',
            fechaInvalida: 'Data baliogabea',
            seleccionaCategoria: 'Kategoria bat hautatu behar duzu',
            seleccionaFecha: 'Data bat hautatu behar duzu',
            sinConexion: 'Konexio errorea',
            tiempoAgotado: 'Konexio denbora agortuta'
        },
        confirmaciones: {
            guardar: 'Aldaketak gorde nahi dituzu?',
            eliminar: 'Ziur zaude elementu hau ezabatu nahi duzula?',
            cancelar: 'Eragiketa hau utzi nahi duzu?',
            salirSinGuardar: 'Aldaketak gorde gabe irten nahi duzu?'
        }
    },
    en: {
        app: {
            titulo: 'Financial Dashboard'
        },
        temas: {
            azul: 'Professional Blue',
            verde: 'Modern Green',
            naranja: 'Energetic Orange',
            turquesa: 'Fresh Turquoise',
            purpura: 'Modern Purple',
            rojo: 'Elegant Red',
            indigo: 'Soft Indigo',
            teal: 'Professional Teal',
            gris: 'Corporate Gray',
            rosado: 'Modern Pink',
            cian: 'Vibrant Cyan',
            lima: 'Fresh Lime',
            esmeralda: 'Premium Emerald',
            ambar: 'Golden Amber',
            violeta: 'Mystic Violet',
            fresa: 'Strawberry Pink',
            oceano: 'Deep Ocean',
            bosque: 'Green Forest',
            atardecer: 'Sunset',
            medianoche: 'Dark Midnight',
            neon: 'Cyberpunk Neon',
            mint: 'Soft Mint',
            coral: 'Tropical Coral',
            lavanda: 'Elegant Lavender',
            grisminimal: 'Minimalist Gray',
            bronce: 'Vintage Bronze',
            cielo: 'Clear Sky'
        },
        periodos: {
            un_mes: '1 Month',
            tres_meses: '3 Months',
            seis_meses: '6 Months',
            un_anio: '1 Year',
            cinco_anios: '5 Years',
            diez_anios: '10 Years'
        },
        resumen: {
            totalIngresos: 'Total Income',
            totalGastos: 'Total Expenses',
            saldo: 'Balance',
            totalImpuestos: 'Total Taxes',
            impuestosPre: 'Pre',
            impuestosPost: 'Post',
            totalHucha: 'Total Piggy Bank'
        },
        tema: {
            cambiarTema: '🎨 Theme:',
            seleccionar: 'Select theme',
            claro: 'Light',
            oscuro: 'Dark',
            automático: 'Automatic'
        },
        idioma: {
            seleccionar: '🌐 Select language:',
            espanol: 'Español',
            ingles: 'English',
            portugues: 'Português',
            frances: 'Français'
        },
        hucha: {
            concepto: 'Concept',
            cantidad: 'Amount'
        },
        nav: {
            categorias: 'Categories',
            gastos: 'Expenses',
            ingresos: 'Income',
            impuestos: 'Taxes',
            dashboard: 'Dashboard',
            hucha: 'Piggy Bank'
        },
        dashboard: {
            titulo: 'Financial Summary',
            periodoRapido: 'Quick Period',
            desde: 'From',
            hasta: 'To',
            desdeDate: 'Select start date',
            hastaDate: 'Select end date',
            actualizar: 'Update',
            totalPeriodo: 'Period Totals',
            gastosPorMes: 'Expenses by Month',
            todasCategorias: 'All categories',
            ingresos: 'Income',
            gastos: 'Expenses',
            ahorros: 'Savings',
            ingresosPorCategoria: 'Income by Category',
            gastosPorCategoria: 'Expenses by Category',
            media: 'Mean',
            varianza: 'Variance',
            desviacion: 'Std dev',
            mediaMensualTotal: 'Monthly mean total',
            impuestosCategoria: 'Taxes',
            errorHastaMenorDesde: 'The "to" date cannot be earlier than the "from" date',
            seleccionaRango: 'Please select a date range'
        },
        categorias: {
            titulo: 'Manage Categories',
            gastos: 'Expenses',
            ingresos: 'Income',
            categoriasGasto: 'Expense Categories',
            categoriasIngreso: 'Income Categories',
            nuevaCategoria: 'New category...',
            noHayCategoriasGasto: 'No expense categories',
            noHayCategoriasIngreso: 'No income categories',
            categoriaAgregada: 'Category added successfully',
            categoriaEliminada: 'Category deleted successfully',
            categoriaActualizada: 'Category updated successfully'
        },
        gastos: {
            titulo: 'Manage Expenses',
            puntuales: 'One-time Expenses',
            mensuales: 'Monthly Expenses',
            descripcion: 'Description...',
            desde: 'From',
            hasta: 'To',
            monto: 'Amount',
            mostrarAntiguos: 'Show old',
            ocultarAntiguos: 'Hide old',
            fraccionar: 'Split',
            noHayGastos: 'No expenses recorded',
            gastoAgregado: 'Expense added successfully',
            gastoEliminado: 'Expense deleted successfully',
            gastoActualizado: 'Expense updated successfully',
            validarFecha: 'Please select a valid date',
            validarMonto: 'Please enter a valid amount',
            validarCategoria: 'Please select a category'
        },
        ingresos: {
            titulo: 'Manage Income',
            puntuales: 'One-time Income',
            mensuales: 'Monthly Income',
            cuenta_remunerada: 'Remunerated Account',
            descripcion: 'Description...',
            desde: 'From',
            hasta: 'To',
            bruto: 'Gross',
            aportacionInicial: 'Initial Contribution',
            aportacionMensual: 'Monthly Contribution',
            interes: 'Interest (%)',
            interesGenerado: 'Generated Interest',
            mostrarAntiguos: 'Show old',
            ocultarAntiguos: 'Hide old',
            noHayIngresos: 'No income recorded',
            ingresoAgregado: 'Income added successfully',
            ingresoEliminado: 'Income deleted successfully',
            ingresoActualizado: 'Income updated successfully',
            validarFecha: 'Please select a valid date',
            validarMonto: 'Please enter a valid amount',
            validarCategoria: 'Please select a category',
            assets: 'Assets',
            noHayCambios: 'No changes',
            descripcionRequerida: 'Description required',
            categoriaRequerida: 'Category required',
            montoInvalido: 'Invalid amount',
            fechaRequerida: 'Date required',
            formatoDesde: "The 'From' field must have format YYYY-MM",
            formatoHasta: "The 'To' field must have format YYYY-MM",
            aportacionInvalida: 'Invalid monthly contribution',
            interesInvalido: 'Invalid interest',
            seleccionaFecha: 'Select a date',
            ingresaDescripcion: 'Enter a description',
            seleccionaCategoria: 'Select a category',
            ingresaDesde: "Enter the 'from' month in YYYY-MM format",
            ingresaHasta: "Enter the 'to' month in YYYY-MM format",
            montoInicialInvalido: 'Invalid initial amount',
            desdeNoMayorHasta: "The 'from' month cannot be greater than 'to'",
            ingresaNombreCompania: 'Enter the company name',
            ingresaTicker: 'Enter the ticker',
            accionesInvalidas: 'Invalid number of shares',
            precioCompraInvalido: 'Invalid purchase price',
            precioVentaInvalido: 'Please enter a valid sale price',
            confirmarVenta: 'Confirm sale of {shares} shares of {company} at {price} per share?',
            ventaExitosa: 'Sale successful. Profit registered: {profit}',
            errorVenta: 'Error: {error}',
            errorProcesarVenta: 'Error processing sale',
            eliminarAsset: 'Delete this asset?',
            company: 'Company',
            ticker: 'Ticker',
            shares: 'Shares',
            purchasePrice: 'Purchase Price',
            totalInvestment: 'Total Invested',
            currentPrice: 'Current Price',
            currentValue: 'Current Value',
            diffPercent: 'Diff. %',
            diffAmount: 'Diff. €',
            sellAsset: 'Sell Asset',
            salePrice: 'Sale Price',
            saleValue: 'Sale Value',
            profit: 'Profit/Loss',
            confirmSale: 'Confirm Sale',
            placeholderDescripcion: 'Description...',
            placeholderMonto: '0.00',
            placeholderYYYYMM: 'YYYY-MM',
            placeholderCompany: 'Apple Inc.',
            placeholderTicker: 'AAPL',
            placeholderShares: '10',
            placeholderPrice: '150.00'
        },

        // ===== TAXES =====
        taxes: {
            agregarPuntual: 'Add One-time Tax',
            agregarMensual: 'Add Monthly Tax',
            impuestoAgregado: 'Tax added successfully',
            impuestoEliminado: 'Tax deleted successfully',
            impuestoActualizado: 'Tax updated successfully',
            desde: 'From',
            hasta: 'To'
        },
        // ===== FORMULARIOS =====
        formularios: {
            guardar: 'Save',
            cancelar: 'Cancel',
            editar: 'Edit',
            eliminar: 'Delete',
            agregar: 'Add',
            buscar: 'Search',
            nombre: 'Name',
            descripcion: 'Description',
            cantidad: 'Quantity',
            monto: 'Amount',
            categoria: 'Category',
            fecha: 'Date',
            desde: 'From',
            hasta: 'To',
            bruto: 'Gross',
            interes: 'Interest',
            accion: 'Action',
            acciones: 'Actions',
            obligatorio: 'Required field',
            confirmarEliminar: 'Are you sure you want to delete this?',
            si: 'Yes',
            no: 'No',
            cerrar: 'Close',
            aceptar: 'Accept',
            rechazar: 'Reject'
        },

        // ===== BOTONES =====
        botones: {
            agregar: 'Add',
            actualizar: 'Update',
            editar: 'Edit',
            eliminar: 'Delete',
            guardar: 'Save',
            cancelar: 'Cancel'
        },

        // ===== TABS =====
        tabs: {
            puntuales: 'One-time',
            mensuales: 'Monthly'
        },
        mensajes: {
            exito: 'Operation completed successfully',
            error: 'An error occurred',
            cargando: 'Loading...',
            noHayDatos: 'No data available',
            seleccionaRango: 'Select a date range',
            categoriasCargadas: 'Categories loaded',
            dashboardActualizado: 'Dashboard updated',
            errorCargando: 'Error loading data',
            errorGuardando: 'Error saving data',
            errorEliminando: 'Error deleting data',
            validacionError: 'Please fill in all required fields',
            confirmacion: 'Confirmation required'
        },
        tablas: {
            sinResultados: 'No results',
            fecha: 'Date',
            descripcion: 'Description',
            monto: 'Amount',
            categoria: 'Category',
            acciones: 'Actions',
            cargando: 'Loading...',
            mostrandoRegistros: 'Showing {0} of {1} records',
            siguiente: 'Next',
            anterior: 'Previous',
            primera: 'First',
            ultima: 'Last',
            porPagina: 'Records per page'
        },
        errores: {
            campoObligatorio: 'This field is required',
            formatoInvalido: 'Invalid format',
            montoNegativo: 'Amount cannot be negative',
            fechaInvalida: 'Invalid date',
            seleccionaCategoria: 'You must select a category',
            seleccionaFecha: 'You must select a date',
            sinConexion: 'Connection error',
            tiempoAgotado: 'Connection timeout'
        },
        confirmaciones: {
            guardar: 'Do you want to save the changes?',
            eliminar: 'Are you sure you want to delete this item?',
            cancelar: 'Do you want to cancel this operation?',
            salirSinGuardar: 'Do you want to exit without saving changes?'
        }
    },

    pt: {
        app: {
            titulo: 'Painel Financeiro'
        },
        temas: {
            azul: 'Azul Profissional',
            verde: 'Verde Moderno',
            naranja: 'Laranja Energético',
            turquesa: 'Turquesa Fresco',
            purpura: 'Púrpura Moderno',
            rojo: 'Vermelho Elegante',
            indigo: 'Índigo Suave',
            teal: 'Teal Profissional',
            gris: 'Cinza Corporativo',
            rosado: 'Rosa Moderno',
            cian: 'Ciano Vibrante',
            lima: 'Lima Fresco',
            esmeralda: 'Esmeralda Premium',
            ambar: 'Âmbar Dourado',
            violeta: 'Violeta Místico',
            fresa: 'Morango Rosa',
            oceano: 'Oceano Profundo',
            bosque: 'Floresta Verde',
            atardecer: 'Pôr do Sol',
            medianoche: 'Meia-Noite Escura',
            neon: 'Neon Ciberpunk',
            mint: 'Menta Suave',
            coral: 'Coral Tropical',
            lavanda: 'Lavanda Elegante',
            grisminimal: 'Cinza Minimalista',
            bronce: 'Bronze Vintage',
            cielo: 'Céu Claro'
        },
        periodos: {
            un_mes: '1 Mês',
            tres_meses: '3 Meses',
            seis_meses: '6 Meses',
            un_anio: '1 Ano',
            cinco_anios: '5 Anos',
            diez_anios: '10 Anos'
        },
        resumen: {
            totalIngresos: 'Total de Receitas',
            totalGastos: 'Total de Despesas',
            saldo: 'Saldo',
            totalImpuestos: 'Total de Impostos',
            impuestosPre: 'Pré',
            impuestosPost: 'Pós',
            totalHucha: 'Total Poupança'
        },
        tema: {
            cambiarTema: '🎨 Tema:',
            seleccionar: 'Selecionar tema',
            claro: 'Claro',
            oscuro: 'Escuro',
            automático: 'Automático'
        },
        idioma: {
            seleccionar: '🌐 Selecionar idioma:',
            espanol: 'Español',
            ingles: 'English',
            portugues: 'Português',
            frances: 'Français'
        },
        hucha: {
            concepto: 'Conceito',
            cantidad: 'Valor'
        },
        nav: {
            categorias: 'Categorias',
            gastos: 'Despesas',
            ingresos: 'Receitas',
            impuestos: 'Impostos',
            dashboard: 'Painel',
            hucha: 'Poupança'
        },
        dashboard: {
            titulo: 'Resumo Financeiro',
            periodoRapido: 'Período Rápido',
            desde: 'De',
            hasta: 'Até',
            desdeDate: 'Selecione a data inicial',
            hastaDate: 'Selecione a data final',
            actualizar: 'Atualizar',
            totalPeriodo: 'Totais do Período',
            gastosPorMes: 'Despesas por Mês',
            todasCategorias: 'Todas as categorias',
            ingresos: 'Receitas',
            gastos: 'Despesas',
            ahorros: 'Poupança',
            ingresosPorCategoria: 'Receitas por Categoria',
            gastosPorCategoria: 'Despesas por Categoria',
            media: 'Média',
            varianza: 'Variância',
            desviacion: 'Desvio padrão',
            mediaMensualTotal: 'Média mensal total',
            impuestosCategoria: 'Impostos',
            errorHastaMenorDesde: 'A data "até" não pode ser anterior à data "de"',
            seleccionaRango: 'Por favor selecione um intervalo de datas'
        },
        categorias: {
            titulo: 'Gerenciar Categorias',
            gastos: 'Despesas',
            ingresos: 'Receitas',
            categoriasGasto: 'Categorias de Despesa',
            categoriasIngreso: 'Categorias de Receita',
            nuevaCategoria: 'Nova categoria...',
            noHayCategoriasGasto: 'Nenhuma categoria de despesa',
            noHayCategoriasIngreso: 'Nenhuma categoria de receita',
            categoriaAgregada: 'Categoria adicionada com sucesso',
            categoriaEliminada: 'Categoria excluída com sucesso',
            categoriaActualizada: 'Categoria atualizada com sucesso'
        },
        gastos: {
            titulo: 'Gerenciar Despesas',
            puntuales: 'Despesas Pontuais',
            mensuales: 'Despesas Mensais',
            descripcion: 'Descrição...',
            desde: 'De',
            hasta: 'Até',
            monto: 'Valor',
            mostrarAntiguos: 'Mostrar antigos',
            ocultarAntiguos: 'Ocultar antigos',
            fraccionar: 'Dividir',
            noHayGastos: 'Nenhuma despesa registrada',
            gastoAgregado: 'Despesa adicionada com sucesso',
            gastoEliminado: 'Despesa excluída com sucesso',
            gastoActualizado: 'Despesa atualizada com sucesso',
            validarFecha: 'Por favor selecione uma data válida',
            validarMonto: 'Por favor insira um valor válido',
            validarCategoria: 'Por favor selecione uma categoria'
        },
        ingresos: {
            titulo: 'Gerenciar Receitas',
            puntuales: 'Receitas Pontuais',
            mensuales: 'Receitas Mensais',
            cuenta_remunerada: 'Conta Remunerada',
            descripcion: 'Descrição...',
            desde: 'De',
            hasta: 'Até',
            bruto: 'Bruto',
            aportacionInicial: 'Contribuição Inicial',
            aportacionMensual: 'Contribuição Mensal',
            interes: 'Juros (%)',
            interesGenerado: 'Juros Gerados',
            mostrarAntiguos: 'Mostrar antigos',
            ocultarAntiguos: 'Ocultar antigos',
            noHayIngresos: 'Nenhuma receita registrada',
            ingresoAgregado: 'Receita adicionada com sucesso',
            ingresoEliminado: 'Receita excluída com sucesso',
            ingresoActualizado: 'Receita atualizada com sucesso',
            validarFecha: 'Por favor selecione uma data válida',
            validarMonto: 'Por favor insira um valor válido',
            validarCategoria: 'Por favor selecione uma categoria',
            assets: 'Ativos',
            noHayCambios: 'Sem alterações',
            descripcionRequerida: 'Descrição obrigatória',
            categoriaRequerida: 'Categoria obrigatória',
            montoInvalido: 'Valor inválido',
            fechaRequerida: 'Data obrigatória',
            formatoDesde: "O campo 'De' deve ter formato AAAA-MM",
            formatoHasta: "O campo 'Até' deve ter formato AAAA-MM",
            aportacionInvalida: 'Contribuição mensal inválida',
            interesInvalido: 'Juros inválidos',
            seleccionaFecha: 'Selecione uma data',
            ingresaDescripcion: 'Insira uma descrição',
            seleccionaCategoria: 'Selecione uma categoria',
            ingresaDesde: "Insira o mês 'de' no formato AAAA-MM",
            ingresaHasta: "Insira o mês 'até' no formato AAAA-MM",
            montoInicialInvalido: 'Valor inicial inválido',
            desdeNoMayorHasta: "O mês 'de' não pode ser maior que 'até'",
            ingresaNombreCompania: 'Insira o nome da empresa',
            ingresaTicker: 'Insira o ticker',
            accionesInvalidas: 'Número de ações inválido',
            precioCompraInvalido: 'Preço de compra inválido',
            precioVentaInvalido: 'Por favor insira um preço de venda válido',
            confirmarVenta: 'Confirmar venda de {shares} ações de {company} a {price} por ação?',
            ventaExitosa: 'Venda bem-sucedida. Lucro registrado: {profit}',
            errorVenta: 'Erro: {error}',
            errorProcesarVenta: 'Erro ao processar a venda',
            eliminarAsset: 'Excluir este ativo?',
            company: 'Empresa',
            ticker: 'Ticker',
            shares: 'Ações',
            purchasePrice: 'Preço de Compra',
            totalInvestment: 'Total Investido',
            currentPrice: 'Preço Atual',
            currentValue: 'Valor Atual',
            diffPercent: 'Dif. %',
            diffAmount: 'Dif. €',
            sellAsset: 'Vender Ativo',
            salePrice: 'Preço de Venda',
            saleValue: 'Valor de Venda',
            profit: 'Lucro/Prejuízo',
            confirmSale: 'Confirmar Venda',
            placeholderDescripcion: 'Descrição...',
            placeholderMonto: '0.00',
            placeholderYYYYMM: 'AAAA-MM',
            placeholderCompany: 'Apple Inc.',
            placeholderTicker: 'AAPL',
            placeholderShares: '10',
            placeholderPrice: '150.00'
        },

        // ===== IMPOSTOS =====
        taxes: {
            agregarPuntual: 'Adicionar Imposto Pontual',
            agregarMensual: 'Adicionar Imposto Mensal',
            impuestoAgregado: 'Imposto adicionado com sucesso',
            impuestoEliminado: 'Imposto excluído com sucesso',
            impuestoActualizado: 'Imposto atualizado com sucesso',
            desde: 'De',
            hasta: 'Até'
        },
        // ===== FORMULÁRIOS =====
        formularios: {
            guardar: 'Salvar',
            cancelar: 'Cancelar',
            editar: 'Editar',
            eliminar: 'Excluir',
            agregar: 'Adicionar',
            buscar: 'Pesquisar',
            nombre: 'Nome',
            descripcion: 'Descrição',
            cantidad: 'Quantidade',
            monto: 'Valor',
            categoria: 'Categoria',
            fecha: 'Data',
            desde: 'De',
            hasta: 'Até',
            bruto: 'Bruto',
            interes: 'Juros',
            accion: 'Ação',
            acciones: 'Ações',
            obligatorio: 'Campo obrigatório',
            confirmarEliminar: 'Tem certeza de que deseja excluir isto?',
            si: 'Sim',
            no: 'Não',
            cerrar: 'Fechar',
            aceptar: 'Aceitar',
            rechazar: 'Rejeitar'
        },

        // ===== BOTÕES =====
        botones: {
            agregar: 'Adicionar',
            actualizar: 'Atualizar',
            editar: 'Editar',
            eliminar: 'Excluir',
            guardar: 'Salvar',
            cancelar: 'Cancelar'
        },

        // ===== ABAS =====
        tabs: {
            puntuales: 'Pontuais',
            mensuales: 'Mensais'
        },
        mensajes: {
            exito: 'Operação concluída com sucesso',
            error: 'Ocorreu um erro',
            cargando: 'Carregando...',
            noHayDatos: 'Nenhum dado disponível',
            seleccionaRango: 'Selecione um intervalo de datas',
            categoriasCargadas: 'Categorias carregadas',
            dashboardActualizado: 'Painel atualizado',
            errorCargando: 'Erro ao carregar dados',
            errorGuardando: 'Erro ao salvar dados',
            errorEliminando: 'Erro ao excluir dados',
            validacionError: 'Por favor preencha todos os campos obrigatórios',
            confirmacion: 'Confirmação necessária'
        },
        tablas: {
            sinResultados: 'Sem resultados',
            fecha: 'Data',
            descripcion: 'Descrição',
            monto: 'Valor',
            categoria: 'Categoria',
            acciones: 'Ações',
            cargando: 'Carregando...',
            mostrandoRegistros: 'Mostrando {0} de {1} registros',
            siguiente: 'Próximo',
            anterior: 'Anterior',
            primera: 'Primeiro',
            ultima: 'Último',
            porPagina: 'Registros por página'
        },
        errores: {
            campoObligatorio: 'Este campo é obrigatório',
            formatoInvalido: 'Formato inválido',
            montoNegativo: 'O valor não pode ser negativo',
            fechaInvalida: 'Data inválida',
            seleccionaCategoria: 'Você deve selecionar uma categoria',
            seleccionaFecha: 'Você deve selecionar uma data',
            sinConexion: 'Erro de conexão',
            tiempoAgotado: 'Tempo de conexão esgotado'
        },
        confirmaciones: {
            guardar: 'Deseja salvar as alterações?',
            eliminar: 'Tem certeza de que deseja excluir este item?',
            cancelar: 'Deseja cancelar esta operação?',
            salirSinGuardar: 'Deseja sair sem salvar as alterações?'
        }
    },

    fr: {
        app: {
            titulo: 'Tableau de Bord Financier'
        },
        temas: {
            azul: 'Bleu Professionnel',
            verde: 'Vert Moderne',
            naranja: 'Orange Énergétique',
            turquesa: 'Turquoise Frais',
            purpura: 'Violet Moderne',
            rojo: 'Rouge Élégant',
            indigo: 'Indigo Doux',
            teal: 'Teal Professionnel',
            gris: 'Gris Corporatif',
            rosado: 'Rose Moderne',
            cian: 'Cyan Vibrant',
            lima: 'Citron Vert Frais',
            esmeralda: 'Émeraude Premium',
            ambar: 'Ambre Doré',
            violeta: 'Violet Mystique',
            fresa: 'Rose Fraise',
            oceano: 'Océan Profond',
            bosque: 'Forêt Verte',
            atardecer: 'Coucher de Soleil',
            medianoche: 'Minuit Sombre',
            neon: 'Néon Cyberpunk',
            mint: 'Menthe Douce',
            coral: 'Corail Tropical',
            lavanda: 'Lavande Élégante',
            grisminimal: 'Gris Minimaliste',
            bronce: 'Bronze Vintage',
            cielo: 'Ciel Clair'
        },
        periodos: {
            un_mes: '1 Mois',
            tres_meses: '3 Mois',
            seis_meses: '6 Mois',
            un_anio: '1 An',
            cinco_anios: '5 Ans',
            diez_anios: '10 Ans'
        },
        resumen: {
            totalIngresos: 'Revenu Total',
            totalGastos: 'Dépenses Totales',
            saldo: 'Solde',
            totalImpuestos: 'Impôts Totaux',
            impuestosPre: 'Pré',
            impuestosPost: 'Post',
            totalHucha: 'Tirelire Totale'
        },
        tema: {
            cambiarTema: '🎨 Thème:',
            seleccionar: 'Sélectionner le thème',
            claro: 'Clair',
            oscuro: 'Sombre',
            automático: 'Automatique'
        },
        idioma: {
            seleccionar: '🌐 Sélectionner la langue:',
            espanol: 'Español',
            ingles: 'English',
            portugues: 'Português',
            frances: 'Français'
        },
        hucha: {
            concepto: 'Concept',
            cantidad: 'Montant'
        },
        nav: {
            categorias: 'Catégories',
            gastos: 'Dépenses',
            ingresos: 'Revenus',
            impuestos: 'Impôts',
            dashboard: 'Tableau de Bord',
            hucha: 'Tirelire'
        },
        dashboard: {
            titulo: 'Résumé Financier',
            periodoRapido: 'Période Rapide',
            desde: 'Du',
            hasta: 'Au',
            actualizar: 'Mettre à jour',
            totalPeriodo: 'Totaux de la Période',
            gastosPorMes: 'Dépenses par Mois',
            todasCategorias: 'Toutes les catégories',
            ingresos: 'Revenus',
            gastos: 'Dépenses',
            ahorros: 'Économies',
            ingresosPorCategoria: 'Revenus par Catégorie',
            gastosPorCategoria: 'Dépenses par Catégorie',
            media: 'Moyenne',
            varianza: 'Variance',
            desviacion: 'Écart type',
            mediaMensualTotal: 'Moyenne mensuelle totale',
            impuestosCategoria: 'Impôts',
            desdeDate: 'Sélectionnez la date de début',
            hastaDate: 'Sélectionnez la date de fin',
            errorHastaMenorDesde: 'La date "à" ne peut pas être antérieure à la date "de"',
            seleccionaRango: 'Veuillez sélectionner une plage de dates'
        },
        categorias: {
            titulo: 'Gérer les Catégories',
            gastos: 'Dépenses',
            ingresos: 'Revenus',
            categoriasGasto: 'Catégories de Dépenses',
            categoriasIngreso: 'Catégories de Revenus',
            nuevaCategoria: 'Nouvelle catégorie...',
            noHayCategoriasGasto: 'Aucune catégorie de dépenses',
            noHayCategoriasIngreso: 'Aucune catégorie de revenus',
            categoriaAgregada: 'Catégorie ajoutée avec succès',
            categoriaEliminada: 'Catégorie supprimée avec succès',
            categoriaActualizada: 'Catégorie mise à jour avec succès'
        },
        gastos: {
            titulo: 'Gérer les Dépenses',
            puntuales: 'Dépenses Ponctuelles',
            mensuales: 'Dépenses Mensuelles',
            descripcion: 'Description...',
            desde: 'Du',
            hasta: 'Au',
            monto: 'Montant',            mostrarAntiguos: 'Afficher les anciens',
            ocultarAntiguos: 'Masquer les anciens',
            fraccionar: 'Diviser',            noHayGastos: 'Aucune dépense enregistrée',
            gastoAgregado: 'Dépense ajoutée avec succès',
            gastoEliminado: 'Dépense supprimée avec succès',
            gastoActualizado: 'Dépense mise à jour avec succès',
            validarFecha: 'Veuillez sélectionner une date valide',
            validarMonto: 'Veuillez entrer un montant valide',
            validarCategoria: 'Veuillez sélectionner une catégorie'
        },
        ingresos: {
            titulo: 'Gérer les Revenus',
            puntuales: 'Revenus Ponctuels',
            mensuales: 'Revenus Mensuels',
            cuenta_remunerada: 'Compte Rémunéré',
            descripcion: 'Description...',
            desde: 'De',
            hasta: 'À',
            bruto: 'Brut',
            aportacionInicial: 'Contribution Initiale',
            aportacionMensual: 'Contribution Mensuelle',
            interes: 'Intérêt (%)',
            interesGenerado: 'Intérêt Généré',
            mostrarAntiguos: 'Afficher les anciens',
            ocultarAntiguos: 'Masquer les anciens',
            noHayIngresos: 'Aucun revenu enregistré',
            ingresoAgregado: 'Revenu ajouté avec succès',
            ingresoEliminado: 'Revenu supprimé avec succès',
            ingresoActualizado: 'Revenu mis à jour avec succès',
            validarFecha: 'Veuillez sélectionner une date valide',
            validarMonto: 'Veuillez entrer un montant valide',
            validarCategoria: 'Veuillez sélectionner une catégorie',
            assets: 'Actifs',
            noHayCambios: 'Aucun changement',
            descripcionRequerida: 'Description requise',
            categoriaRequerida: 'Catégorie requise',
            montoInvalido: 'Montant invalide',
            fechaRequerida: 'Date requise',
            formatoDesde: "Le champ 'De' doit avoir le format AAAA-MM",
            formatoHasta: "Le champ 'À' doit avoir le format AAAA-MM",
            aportacionInvalida: 'Contribution mensuelle invalide',
            interesInvalido: 'Intérêt invalide',
            seleccionaFecha: 'Sélectionnez une date',
            ingresaDescripcion: 'Entrez une description',
            seleccionaCategoria: 'Sélectionnez une catégorie',
            ingresaDesde: "Entrez le mois 'de' au format AAAA-MM",
            ingresaHasta: "Entrez le mois 'à' au format AAAA-MM",
            montoInicialInvalido: 'Montant initial invalide',
            desdeNoMayorHasta: "Le mois 'de' ne peut pas être supérieur à 'à'",
            ingresaNombreCompania: "Entrez le nom de l'entreprise",
            ingresaTicker: 'Entrez le ticker',
            accionesInvalidas: "Nombre d'actions invalide",
            precioCompraInvalido: "Prix d'achat invalide",
            precioVentaInvalido: 'Veuillez entrer un prix de vente valide',
            confirmarVenta: 'Confirmer la vente de {shares} actions de {company} à {price} par action?',
            ventaExitosa: 'Vente réussie. Profit enregistré: {profit}',
            errorVenta: 'Erreur: {error}',
            errorProcesarVenta: 'Erreur lors du traitement de la vente',
            eliminarAsset: 'Supprimer cet actif?',
            company: 'Entreprise',
            ticker: 'Ticker',
            shares: 'Actions',
            purchasePrice: "Prix d'Achat",
            totalInvestment: 'Total Investi',
            currentPrice: 'Prix Actuel',
            currentValue: 'Valeur Actuelle',
            diffPercent: 'Diff. %',
            diffAmount: 'Diff. €',
            sellAsset: "Vendre l'Actif",
            salePrice: 'Prix de Vente',
            saleValue: 'Valeur de Vente',
            profit: 'Profit/Perte',
            confirmSale: 'Confirmer la Vente',
            placeholderDescripcion: 'Description...',
            placeholderMonto: '0.00',
            placeholderYYYYMM: 'AAAA-MM',
            placeholderCompany: 'Apple Inc.',
            placeholderTicker: 'AAPL',
            placeholderShares: '10',
            placeholderPrice: '150.00'
        },

        // ===== IMPÔTS =====
        taxes: {
            agregarPuntual: 'Ajouter un Impôt Ponctuel',
            agregarMensual: 'Ajouter un Impôt Mensuel',
            impuestoAgregado: 'Impôt ajouté avec succès',
            impuestoEliminado: 'Impôt supprimé avec succès',
            impuestoActualizado: 'Impôt mis à jour avec succès',
            desde: 'Du',
            hasta: 'Au'
        },
        // ===== FORMULAIRES =====
        formularios: {
            guardar: 'Enregistrer',
            cancelar: 'Annuler',
            editar: 'Modifier',
            eliminar: 'Supprimer',
            agregar: 'Ajouter',
            buscar: 'Rechercher',
            nombre: 'Nom',
            descripcion: 'Description',
            cantidad: 'Quantité',
            monto: 'Montant',
            categoria: 'Catégorie',
            fecha: 'Date',
            desde: 'Du',
            hasta: 'Au',
            bruto: 'Brut',
            interes: 'Intérêt',
            accion: 'Action',
            acciones: 'Actions',
            obligatorio: 'Champ requis',
            confirmarEliminar: 'Êtes-vous sûr de vouloir supprimer ceci ?',
            si: 'Oui',
            no: 'Non',
            cerrar: 'Fermer',
            aceptar: 'Accepter',
            rechazar: 'Rejeter'
        },

        // ===== BOUTONS =====
        botones: {
            agregar: 'Ajouter',
            actualizar: 'Mettre à jour',
            editar: 'Modifier',
            eliminar: 'Supprimer',
            guardar: 'Enregistrer',
            cancelar: 'Annuler'
        },

        // ===== ONGLETS =====
        tabs: {
            puntuales: 'Ponctuels',
            mensuales: 'Mensuels'
        },
        mensajes: {
            exito: 'Opération terminée avec succès',
            error: 'Une erreur s\'est produite',
            cargando: 'Chargement...',
            noHayDatos: 'Aucune donnée disponible',
            seleccionaRango: 'Sélectionnez une plage de dates',
            categoriasCargadas: 'Catégories chargées',
            dashboardActualizado: 'Tableau de bord mis à jour',
            errorCargando: 'Erreur lors du chargement des données',
            errorGuardando: 'Erreur lors de l\'enregistrement des données',
            errorEliminando: 'Erreur lors de la suppression des données',
            validacionError: 'Veuillez remplir tous les champs obligatoires',
            confirmacion: 'Confirmation requise'
        },
        tablas: {
            sinResultados: 'Aucun résultat',
            fecha: 'Date',
            descripcion: 'Description',
            monto: 'Montant',
            categoria: 'Catégorie',
            acciones: 'Actions',
            cargando: 'Chargement...',
            mostrandoRegistros: 'Affichage de {0} sur {1} enregistrements',
            siguiente: 'Suivant',
            anterior: 'Précédent',
            primera: 'Premier',
            ultima: 'Dernier',
            porPagina: 'Enregistrements par page'
        },
        errores: {
            campoObligatorio: 'Ce champ est obligatoire',
            formatoInvalido: 'Format invalide',
            montoNegativo: 'Le montant ne peut pas être négatif',
            fechaInvalida: 'Date invalide',
            seleccionaCategoria: 'Vous devez sélectionner une catégorie',
            seleccionaFecha: 'Vous devez sélectionner une date',
            sinConexion: 'Erreur de connexion',
            tiempoAgotado: 'Délai d\'attente de connexion dépassé'
        },
        confirmaciones: {
            guardar: 'Voulez-vous enregistrer les modifications ?',
            eliminar: 'Êtes-vous sûr de vouloir supprimer cet élément ?',
            cancelar: 'Voulez-vous annuler cette opération ?',
            salirSinGuardar: 'Voulez-vous quitter sans enregistrer les modifications ?'
        }
    }
};