name: Release Windows EXE Only


on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Buscar el archivo .exe
        id: find_exe
        run: |
          $exe = Get-ChildItem -Path dist -Filter *.exe -Recurse | Select-Object -First 1
          if ($exe) {
            echo "exe_path=$($exe.FullName)" >> $env:GITHUB_OUTPUT
          } else {
            echo "No se encontró el .exe en dist/"
            exit 1
          }

      - name: Crear release en GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_exe.outputs.exe_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
